; Board JSON stored in boards/ folder as PlatformIO doesn't include the latest ESP32-S3 DevKitC-1-N16R8V board definition yet. Once it does, we can switch to using the built-in board definition instead of the custom one.
; https://github.com/handledexception/platform-espressif32/blob/esp32-s3-devkitc-1-n16r8v/boards/esp32-s3-devkitc-1-n16r8v.json

[env:esp32dev]
platform = espressif32
board = esp32-s3-devkitc-1-n16r8v
framework = arduino
board_build.partitions = default_16MB.csv

lib_deps = 
    https://github.com/pschatzmann/arduino-audio-tools.git
    https://github.com/pschatzmann/arduino-libhelix.git
    mathertel/OneButton@^2.5.0
    mathertel/RotaryEncoder@^1.5.3
    marcmerlin/FastLED NeoMatrix@^1.2
build_flags = 
    -DCORE_DEBUG_LEVEL=5
    -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-function -Wno-format-extra-args
monitor_speed = 115200
monitor_filters = esp32_exception_decoder