[platformio]
default_envs = esp32dev-n16r8

[env:esp32dev-n16r8]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; https://github.com/sivar2311/ESP32-PlatformIO-Flash-and-PSRAM-configurations#esp32-s3-wroom-11u-n16r8
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.partitions = default_16MB.csv
board_build.extra_flags = 
  -DBOARD_HAS_PSRAM

lib_deps = 
    https://github.com/pschatzmann/arduino-audio-tools.git
    https://github.com/pschatzmann/arduino-libhelix.git
    mathertel/OneButton@^2.5.0
    mathertel/RotaryEncoder@^1.5.3
    marcmerlin/FastLED NeoMatrix@^1.2
build_flags = 
    -DCORE_DEBUG_LEVEL=5
    -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-function -Wno-format-extra-args
monitor_speed = 115200
monitor_filters = esp32_exception_decoder


[env:esp32dev]
platform = espressif32
board = esp32dev    
framework = arduino

lib_deps = 
    https://github.com/pschatzmann/arduino-audio-tools.git
    https://github.com/pschatzmann/arduino-libhelix.git
    mathertel/OneButton@^2.5.0
    mathertel/RotaryEncoder@^1.5.3
    marcmerlin/FastLED NeoMatrix@^1.2
build_flags = 
    -DCORE_DEBUG_LEVEL=2      
    -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-function -Wno-format-extra-args
monitor_speed = 115200
monitor_filters = esp32_exception_decoder